version: '3.8'

services:
  dnsmasq:
    container_name: dnsmasq
    image: andyshinn/dnsmasq:latest
    ports:
      - "53:53/udp"
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    command: ["-k"]
    networks:
      - klimanetwork

  mysqldb:
    container_name: asgard
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: klimaralley
    ports:
      - "3306:3306"
    networks:
      - klimanetwork
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
        
  spring:
    container_name: bifrost
    depends_on:
      mysqldb:
        condition: service_healthy
    build:
      context: klimaralley-server
      dockerfile: Dockerfile
    image: klimaserver:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/klimaralley
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
    networks:
      - klimanetwork

  klimaralley-hub:
    container_name: klimaralley
    image: klimaralley-hub:latest
    build:
      context: ./klimaralley-hub
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - klimanetwork
    depends_on:
      - dnsmasq
      - spring

  klimaralley-flut:
    container_name: flut
    image: klimaralley-flut:latest
    build:
      context: klimaralley-flut
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - klimanetwork
    depends_on:
      - dnsmasq
      - spring

  klimaralley-recycling:
    container_name: recycling
    image: klimaralley-recycling:latest
    build:
      context: klimaralley-recycling
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - klimanetwork
    depends_on:
      - dnsmasq
      - spring

  klimaralley-wasserarm:
    container_name: wasserarm
    image: klimaralley-wasserarm:latest
    build:
      context: klimaralley-wasserarm
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    networks:
      - klimanetwork
    depends_on:
      - dnsmasq
      - spring

  nginx:
    container_name: midgard
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - klimanetwork
    depends_on:
      - klimaralley-flut
      - klimaralley-hub
      - klimaralley-recycling
      - klimaralley-wasserarm

networks:
  klimanetwork:
    driver: bridge
